name: Release DevOps with Docker

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jpparkkari/coursepage:latest
    #deploy
    #- name: deploy
    #  if: github.event_name == 'push' && contains(github.event.head_commit.message, '#skip') == false
    #  uses: gonuit/heroku-docker-deploy@v1.3.2 # This is the action
    #  with:
    #    heroku_api_key: ${{secrets.HEROKU_API_KEY}}
    #    heroku_app_name: "jpparkkari-coursepage" #Must be unique in Heroku
    #    email: "j-p.parkkari@iki.fi"
    #    dockerfile_directory: ./
    #    dockerfile_name: Dockerfile
    #    docker_options: "--no-cache"
    #    process_type: web
